# provision machine and deploy code

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - base
    - configure
    - nginx
  handlers:
    - include: handlers/handlers.yml

- include: deploy.yml
